### ISSUE TITLE
Unclear tab behaviour on report

### ISSUE THREAD

**Issue by ldodds** [theodi/pathway#134]
On the detail & improvement tabs in the report pages, when I switch between activities it can be a bit confusing about which tab is active.

The list of activities down the page are grouped by dimension, and there can be one active tab in each. This means if you've viewed a couple of activities, it can be unclear which one is currently displayed as several tabs are highlighted.

**Comment by sumikasan** [comment]
Suggested improvements tab needs fixing still:

![uploads/f3251ec5-57f1-40ca-bcee-4f599e045cee/Screen Shot 2015-05-05 at 15.45.34.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff3251ec5-57f1-40ca-bcee-4f599e045cee%2FScreen+Shot+2015-05-05+at+15.45.34.png)

**Comment by ldodds** [comment]
Can you retest this please, as its working on both tabs for me
