### ISSUE TITLE
Start new assessment page - minor styling issues

### ISSUE THREAD

**Issue by sumikasan** [theodi/pathway#146]
The styling looks different to the html mock up (http://upcloseandpixelated.com/ODMAT/pages/assessment-overview.html)

* [x] 'Continue assessment' should be 'Start assessment' if the use has not started answering any questions

When the user started using it, then the button should say 'Continue assessment'

* [x] New assessment - it's not obvious that you can change the name. We need to make this more prominent and make it into a button (use the same button style as 'Begin' but in Orange and appear adjacent to the heading "New assessment"

* [x] Background information - again, this is not obvious. Make 'Edit' a button (again in Orange), to appear adjacent to the heading "Background information"

* [x] Dimension should be called 'Theme'

* [x] Icon (i) does not link to anything. It should link, or show a pop up help text

* [ ] Colouring used on tick is too strong/bold, it needs to be fainter as per mock-up

* [x] The status 'Edit' should be orange colour, not grey

* [x] Font for the texts to display the 'Background information' - this should be in the smaller font

* [x] Begin should be 'Start' to be consistent with other phrases we have used so far across the site

**Comment by ldodds** [comment]
Ticked off a couple of these as I've addressed them in other issues

**Comment by ldodds** [comment]
Also, the colouring on the tick is the same green as on the mockup?
