### ISSUE TITLE
External supporting resources Text field is unclear

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#179]
Is the "Text" field meant to capture some additional information that wasn't entered in the "Please enter any additional information or supporting evidence" answer, or its it text that the Link provided will be placed behind?

![screenshot 2015-04-15 06 04 07](https://cloud.githubusercontent.com/assets/9379524/7146293/dda365ba-e335-11e4-9cd9-9e9ce900e5a0.png)

I think providing an example end result of the assessment process (screen shot, pdf report?) before people start the assessment would help. Perhaps also an information icon beside the field would help e.g. 

![screenshot 2015-04-15 06 14 08](https://cloud.githubusercontent.com/assets/9379524/7146451/ebad63bc-e336-11e4-9019-224c97d21f47.png)

**Comment by Stephen-Gates** [comment]
Oh! just discovered the hover over tip on the "Text" label. Too subtle for me ;-)

**Comment by ldodds** [comment]
Have added placeholder text to the field which should indicate what each of the boxes are for.

Have also moved the button so its next to the Link field.
