### ISSUE TITLE
Skip a question

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#183]
I would like to be able to skip a question if I'm unsure of the answer and continue on to the next question in the survey. At present, I'm forced to answer a question before I can proceed.

**Comment by sumikasan** [comment]
@ldodds this is something we may want to review?

**Comment by ldodds** [comment]
The questionnaire isn't designed in a way that questions can be skipped. 

Its basically a tree structure. A No answer means you've reached a "leaf" of the tree and a score is assigned.

If you were to skip a question then you may end up answering unnecessary questions as changing your answer to "No" for the skipped question will make them redundant.

This is something we could review for future releases, but difficult to implement currently where we've been trying to ensure that users answer only the minimum number of questions.

**Comment by Stephen-Gates** [comment]
Happy to close this if required. It was a nice to have.
