### ISSUE TITLE
User can share authorised link to assessment results

### ISSUE THREAD

**Issue by ldodds** [theodi/pathway#19]
User can request a "sharing link" that can be used to give an anonymous user access to view the summary and detailed responses to an assessment.

This allows them to share results more widely with their organisation. Or, if they choose, publicly.

**Comment by sumikasan** [comment]
It's very subtle - I suggest we change from 'Sharing link' to:

- [ ] Link should be called "Copy shareable link"
- [ ] when user clicks the link, the link is 'copied'
- [ ] user sees the message that 'Link copied to clipboard'

If this is requires too much effort, we should at least say:
"Copy and paste the link to share this report." (don't forget the full stop)
and show the link in a URL box (standard practice - user may know always know how to copy the link URL).

**Comment by ldodds** [comment]
I've switched this to put the URL in a box, but I've just tweaked the existing wording:

"Copy the following link to share your report with colleagues or to publish it openly for others to read."

I think it reads better than just "Copy and paste the link to share this report."?
