### ISSUE TITLE
Add some instructions to registration page

### ISSUE THREAD

**Issue by ldodds** [theodi/pathway#203]

**Comment by Stephen-Gates** [comment]
@ldodds As we are hoping to add country to the registration page, could we include some instructions for you? I was thinking something like this (captures your tip in #284)

<img width="1117" alt="screenshot 2016-09-24 08 54 38" src="https://cloud.githubusercontent.com/assets/9379524/18803565/89a90b78-8234-11e6-914d-d782eaf67b10.png">

**Comment by Stephen-Gates** [comment]
@ldodds I think this can be closed if you're happy with the new http://pathway.theodi.org/users/sign_up

**Comment by Floppy** [comment]
:+1:
