### ISSUE TITLE
confirmation on completion of assessment

### ISSUE THREAD

**Issue by ldodds** [theodi/pathway#209]

**Comment by sumikasan** [comment]
I suggest we change the button to say 'See my scores'.

And when someone clicks 'See my scores', there should be a warning message (like when the user clicks 'exit' button) to warn the user that 'Your answers have been set; you will not be able to edit after this point' or something like that?

**Comment by ldodds** [comment]
What do you think of the text/changes I've made so far? Currently it has "Complete assessment" on the button, plus some additional text underneath
