### ISSUE TITLE
Relabel report tabs

### ISSUE THREAD

**Issue by ldodds** [theodi/pathway#217]
* Summary
* Maturity scores
* Your answers
* Action plan
* Background

**Comment by sumikasan** [comment]
I don't see any changes. I suggest we park this for now. 

![uploads/f749a2f5-2a59-42a3-8f03-802fe0894fe3/Screen Shot 2015-05-05 at 16.36.32.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff749a2f5-2a59-42a3-8f03-802fe0894fe3%2FScreen+Shot+2015-05-05+at+16.36.32.png)

**Comment by ldodds** [comment]
I ended up using slightly different text than in the report, but the tab headings are different to what we had before which was Summary/Activities/Detail/Improvements/Background.
