### ISSUE TITLE
Statistics for country

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#273]
To help ODI Nodes report on their success at encouraging organisations to improve, enable statistics to be filtered by geographic area (initially country level)

**Comment by sumikasan** [comment]
@Stephen-Gates - thanks for your feedback. 

We would love to continue improving the tool and we hope we can get a sponsor to fund a feature request such as this!

**Comment by Stephen-Gates** [comment]
Hi @sumikasan are you saying that the ODI has ceased development on the open data maturity assessment tool? 

- Will you take the current beta functionality through to final release?
- Will you perform bug fixes to the production release?
- Will you only improve the open data maturity assessment tool if someone pays you?
- Are there any conditions when the ODI will fund improvements in the tool? If so, what are these conditions?
- Are you planning to publish (outside Github) a list of proposed features and crowdsource funds for each?

I'd love to see a product roadmap for this (and other) ODI tools so we can advocate their use or provide appropriate cautionary advice.

**Comment by sumikasan** [comment]
@Stephen-Gates - sorry to alarm you; there is no plan to stop supporting the tool. I only meant to say we are prioritising improvements to currently implemented features, as based on beta feedback at this moment in time (sorry, it's late here in the UK so apologies for any misunderstanding).

**Comment by Stephen-Gates** [comment]
@sumikasan I'd like to understand the sponsorship options. It may be something I could assist with. Please email details.

**Comment by Stephen-Gates** [comment]
My idea is to add fields to the user account (parent, sector, country), to support reporting such as: 

- Compare your organisation with all other organisations within your “parent organisation”  (e.g. your department compared to all other departments in the same government.)
- Comparing your organisation against another benchmark (country, sector).
- Comparing benchmarks (e.g. Australia against all other countries. UK compared to USA)
- Show your progress over time.

As a potential quick way to implement some of this, could the last part of each organisations web address (e.g. gov.au or .co.nz) be added to the data download? This would allow some improved reporting by sector and country.

**Comment by Stephen-Gates** [comment]
[Google slides](https://docs.google.com/presentation/d/1FCHtT_qHaxq2h2GukvJoK5T00rkyOR55TTWB51t6tzw/edit?usp=sharing) showing proposed changes. Comments welcome.

**Comment by Stephen-Gates** [comment]
Closed by #314
