### ISSUE TITLE
What's needed to get out of Beta?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#282]
We're proposing adoption of the Open Data Maturity Model and Pathway tool for adoption across our Government departments. 

What is needed get the tool out of Beta and surfaced on theODI.org site?

It we be easier to convince stakeholder to adopt a production-ready tool rather than a beta site.

**Comment by ldodds** [comment]
One of the most important things we're looking for is just feedback on the service as it stands. That includes not just functionality (improvements, bug reports) but how useful it is, and how well the questionnaire works. Here in the UK we have a number of orgs that are trialing it out internally, doing their first assessments. We're hoping to get more of the data.gov.uk publishing organisations signed up too, hopefully over the coming months. It's been really useful to have your feedback too, to provide some wider context.

We've not time-boxed the beta period yet, as we wanted to see what level of feedback and engagement we receive.

@sumikasan will be responsible for collating the feedback and identifying the necessary steps to move us forward. We're also working to identify how to resource the project as we move forward.

I want to reassure you though that this is seen as a useful and important tool by us at the ODI, so it shouldn't languish in beta, we just don't have a firm product roadmap currently.

**Comment by sumikasan** [comment]
@Stephen-Gates - I am sending out a survey to find out how they currently use the tool to help us understand what the Minimum Marketable Product looks like. I will be sharing our current thinking once we have more data/info. With the budget planning starting soon, I would like to have a draft plan in place in August if not sooner for wider input / review. So watch this space!

**Comment by Stephen-Gates** [comment]
@ldodds @sumikasan thank you for your comments. I think you have a Minimum Marketable Product now. It has helped us engage stakeholders, understand our strengths and weaknesses and we had fun as a team assessing and planning improvements. My view is it probably only needs tweaking on the help text but that will come through use. Better sharing/reporting would also be nice. Look forward to the draft.

**Comment by Floppy** [comment]
We're building the 1.0 list in https://github.com/theodi/pathway/milestones/1.0 now, so hopefully we'll be able to get beta escape velocity soon :)
