### ISSUE TITLE
Number of questions ≠ Score denominator 

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#286]
There are 83 questions in [the survey](https://github.com/theodi/pathway/tree/master/survey) but I receive a overall score out on 75.

How does that work?

<img width="393" alt="screenshot 2015-09-15 02 38 28" src="https://cloud.githubusercontent.com/assets/9379524/9855634/e70ed4b4-5b52-11e5-9856-3488d349e3c0.png">

**Comment by ldodds** [comment]
You receive a maturity score out of 5 for each *activity* see the [maturity model spreadsheet](http://theodi.org/maturity-model), not a score per question which wouldn't make sense.

Answering questions locates you on the maturity model for a specific assessment.

**Comment by Stephen-Gates** [comment]
Ok 15 Activities × 5 levels = total of 75 - got it - Thanks
