### ISSUE TITLE
Application has dataset page for public downloads

### ISSUE THREAD

**Issue by ldodds** [theodi/pathway#30]
Should have:

* Licence (UK-OGL v3)
* Embedded DCAT metadata
* Description of data formats
* Link to certificate

**Comment by sumikasan** [comment]
There is no certificate

**Comment by ldodds** [comment]
Creation of the certificate is another issue, see #31

**Comment by sumikasan** [comment]
Note - I suggest we have a documentation or something that actually explains what each of the column heading means for the dataset that people are downloading - e.g. Organisations.

**Comment by ldodds** [comment]
OK that sounds good. Could we have a separate issue for that and then close down this feature?
