### ISSUE TITLE
organisation count wrong on /statistics 

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#308]
On the [statistics heat map](http://pathway.theodi.org/statistics) it states there are 195 registered organisations however the csv download says there are 144 organisations with users and 195 users. Declaring an organisation is optional on user registration.
## Expected Behaviour

Expected behaviour is to state the correct number of users (as this is what the stats show).
Change text to...

> Showing aggregate results for 75 assessments from a total of 195 registered **users**.

OR

Change CSV Statistic names
<img width="506" alt="screenshot 2016-09-24 11 24 42" src="https://cloud.githubusercontent.com/assets/9379524/18805145/920539e4-8249-11e6-8304-a96ae8c58f20.png">
## Current Behaviour

Currently the number of users is reported as the number of organisations

<img width="763" alt="screenshot 2016-09-24 10 35 30" src="https://cloud.githubusercontent.com/assets/9379524/18804901/f0ea88ce-8244-11e6-999a-0e12b84a6205.png">
## Steps to Reproduce (for bugs)
1. view statistics page
2. download the stats http://pathway.theodi.org/statistics/summary.csv 
3. compare the numbers

**Comment by quadrophobiac** [comment]
N registered users across M organisations

**Comment by Stephen-Gates** [comment]
@quadrophobiac  see also #313 

We got very confused between "users" and "organisations" when doing the country-level statistics PR (#312, #314) and tried to clarify things a little on the [download](http://pathway.theodi.org/statistics/data) page. 

Perhaps the change is not in the code but the words used on the page, as suggested in the expected behaviour above.

**Comment by quadrophobiac** [comment]
Thanks @Stephen-Gates - think that distinction between users and organisations could be made clearer in the code at a later date but it is OK to keep it as is for now
