### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#309]
Myself and @grhammo have tried to reset our passwords. We don't receive an email with reset instructions

## Expected Behaviour
We should get a email with instructions to reset our password

## Current Behaviour
We don't receive an email with reset instructions

## Steps to Reproduce (for bugs)

1. go to http://pathway.theodi.org/users/password/new 
2. enter email
3. press "Send my password reset instructions"
4. look in email inbox (nothing!)

## Your Environment

* Chrome Version 53.0.2785.116 m (64-bit)
* Windows 7 Desktop

**Comment by pezholio** [comment]
This was due to missing Mandrill credentials. All is fixed now! :+1:
