### ISSUE TITLE
Editing assessment title and background information is broken

### ISSUE THREAD

**Issue by Floppy** [theodi/pathway#318]
When you click edit on an assessment title, or the background information field, the edit box shows briefly then switches back to the static text.

This showed up by updating capybara in #315 and needs resolving before that can merge.

@Stephen-Gates can you confirm if you see the same thing? @ldodds and I have both replicated it...

**Comment by Floppy** [comment]
Ah, #315 now passes, which is slightly odd, but I do get this on production as well as in dev, so it's still a valid bug.

**Comment by Stephen-Gates** [comment]
I'm still getting this with Safari and Chrome on Mac

**Comment by alexrcoley** [comment]
I'm still getting this issue with Safari, Chrome and Firefox on the Mac.

**Comment by marshallje** [comment]
I'm having the same problem on Internet Explorer 11.

**Comment by rachelwilson** [comment]
Seems to be resolved in 2021 - closing
