### ISSUE TITLE
issue 2 to test octobox - ignore

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/pathway#356]
TheODI GitHub Organisation has authorised Octobox.io to see notifications. Some aren't appearing. See https://github.com/theodi/toolbox/issues/23

Perhaps adding a new issue and not closing it quickly will enable Octobox to see it

**Comment by Stephen-Gates** [comment]
@Floppy can you reply to this to try poke Octobox. It's mainly working for me but I can't get Pathway to show for some reason. Thanks for your help on Octobox - hopefully it's working better for you.

**Comment by Floppy** [comment]
hello - replying :)

**Comment by Stephen-Gates** [comment]
Still can’t see this in octobox but closing

**Comment by Stephen-Gates** [comment]
Oh closing or pressing refresh for the 101th time made this appeat in octobox
